#!/bin/bash
# Spawn a new terminal window and run the server
osascript <<EOF
tell application "Terminal"
    activate
    do script "cd /Users/hughmurrell/Desktop/git_repos/WorkMonitor && source venv/bin/activate && python3 monitorWork_server.py"
end tell
EOF

